name: Deploy frontend application
'on':
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - 
        name: prepare the docker-compose run
        run: |
          ls -l
      - 
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: saw96/devopsproject:latest
      - 
        name: prepare the docker-compose run
        run: |
              mkdir devopsprojcet
              cp docker-compose.yml devopsproject/docker-compose.yml
              cd devopsproject
              docker-compose -H ${{ secrets.HOST_SERVER }} down
              docker-compose -H ${{ secrets.HOST_SERVER }} pull
              docker-compose -H ${{ secrets.HOST_SERVER }} up -d